TARGET = vvvf

SOURCES = Source/Main.c Source/ConfigParser.c Source/ConfigParser.h Source/Parameters.h Source/SPWMGenerator.h Source/SPWMGenerator.c Source/PulsePattern.c Source/PulsePattern.h ThirdParty/tiny-json/tiny-json.h ThirdParty/tiny-json/tiny-json.c

INCLUDE_PATHS = -IThirdParty/tiny-json

VESC_C_LIB_PATH=../
include $(VESC_C_LIB_PATH)rules.mk

